name: egytrip
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.2+1

version: 1.0.2+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.7+2
  provider: ^3.0.0
  cached_network_image: ^2.2.0+1
  http: ^0.12.1
  intl: ^0.16.1
  full_screen_image: ^1.0.2
  selection_menu: ^0.9.0





  # The following adds the Cupertino Icons font to your application.
  #flutter_cupertino_date_picker: ^1.0.26+2
  #  audioplayers: ^0.13.3
  #url_launcher: ^5.5.0
  #  auto_size_text: ^2.1.0
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  country_code_picker: ^1.4.0
  flutter_open_whatsapp: ^0.1.2
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  flutter_page_indicator: ^0.0.3
  flutter_phone_direct_caller: ^1.0.1
  like_button: ^1.0.4
  share: ^0.6.5+4
  flutter_placeholder_textlines: ^1.0.4
  flutter_swiper: ^1.1.6
  upgrader: ^2.8.2
  url_launcher: ^5.7.7




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.8
flutter_native_splash:
  color: "#ff6300"
  image: assets/launcher/splash2.png
  fill: true



  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/hotel.png"
  image_path_android: "assets/launcher/hotel.png"
#  adaptive_icon_background: "assets/launcher/hotel.png"
#  adaptive_icon_foreground: "assets/launcher/hotel.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - lib/lang/en.json
    - lib/lang/fa.json
    - lib/lang/ar.json
    - lib/lang/hi.json
    - assets/image/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada-SemiBold.ttf
          weight: 600

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
